version: '1.0'
services:
  - name: db
    type: mariadb
    version: 10.4
    configuration: StandAlone
    database: piwik
    username: piwik
    userPassword: null
    password: null
    ports:
      - 3306
    remoteAccess: false
    comments:
      userPassword: Password for user "piwik"
    deployTo:
      - matomo

  - name: matomo
    type: docker
    image: matomo
    version: fpm
    ports:
      - 9000
    remoteAccess: false
    volumes:
      - directory: /var/www/html/config
      - directory: /var/www/html/logs
    deployTo:
      - matomo

  - name: adminer
    type: docker
    image: adminer
    version: latest
    ports:
      - 8080
    remoteAccess: false
    env:
      ADMINER_DEFAULT_SERVER: "{{=service('db').getMasterAlias()}}"
    deployTo:
      - matomo

  - name: web
    type: nginx
    version: 1.17
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: matomo
        static: true
        src: ./configs/matomo.conf
      - name: adminer
    deployTo:
      - matomo

hosts:
  - name: matomo
    requirements:
      cores: 1
      memory: 1
